version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine3.15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: DATABASE_NAME_HERE
      POSTGRES_USER: DATABASE_USERNAME_HERE
      POSTGRES_PASSWORD: DATABASE_PASSWORD_HERE
  
  redis:
    container_name: redis
    image: redis:alpine3.15
    restart: always
    ports:
      - 6379:6379

  syrim:
    container_name: bot
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://DATABASE_USERNAME_HERE:DATABASE_PASSWORD_HERE@postgres/DATABASE_NAME_HERE
      DISCORD_TOKEN: DISCORD_TOKEN_HERE
      NEKOBOT_API_KEY: NEKOBOT_API_KEY_HERE
      REDIS_URL: redis://redis@redis:6379
      STATCORD_API_KEY: STATCORD_API_KEY_HERE
    ports:
      - 3000:3000
      - 5555:5555