version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine3.15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  
  redis:
    container_name: redis
    image: redis:alpine3.15
    restart: always
    ports:
      - 6379:6379

  syrim:
    container_name: bot
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
      - 5555:5555