version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine3.15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  syrim:
    container_name: bot
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
